#!/bin/sh

# This script start all test in TEST_HOME
# If one of the var is not set here, it means it have to be set by the caller :
# - TEST_HOME
# SH_OTPS is optionnal

# TEST_HOME Is the dir where all the tests are located
# ACTUAL and EXPECTED are temporary files for the tests
# INFRA_SETTINGS is the python file used by app/infrastructure as a setting file
# PROJECT_FILE Is the project file of age-decision-core

set -eu
alias dir_exist='test -d'
alias file_exist='test -f'


dir_exist $TEST_HOME


export ACTUAL="$TEST_HOME/actual"
export EXPECTED="$TEST_HOME/expected"

export PROJECT_FILE='./project.json'
file_exist $PROJECT_FILE

export INFRA_SETTINGS='./app/infrastructure/config/settings.py'
file_exist $INFRA_SETTINGS

set +u
for file in "${TEST_HOME}/*.test.sh"
do
	# Options facultatifs pour le shell
	sh $SH_OPTS $file
done

rm $ACTUAL
rm $EXPECTED
